remote_theme: luxedo/jekyll-theme-potato-hacker
theme_base: "dark"       # Theme palette (light | dark)
theme_switch: on         # Show color switch (on | off)

# Extra settings
blog: on                 # Show blog tag and post list (on | off)
avatar: on               # Show avatar (on | off)
avatar_image: "assets/img/frac.jpg"
avatar_description: "frac rack 4eva ðŸŽ¶"
highlighter_theme: monokai  # Theme of the syntax_highlighter [base16 |
                            # colorful | github | gruvbox | molokai |
                            # monokai | pastie | thankful_eyes | tulip ]
toolbar_priority:        # Order of the items in the toolbar (except for blog and home)
  - dropdown2
  - About
  - dropdown1

# Collections
collections:
  dropdown:
    output: true
  items:
    output: true
