remote_theme: luxedo/jekyll-theme-potato-hacker
theme_base: "dark"       # Theme palette (light | dark)
theme_switch: on         # Show color switch (on | off)

logo                     : "/assets/img/frac.jpg" # path of logo image to display in the masthead,
# Extra settings
blog: on                 # Show blog tag and post list (on | off)
avatar: on               # Show avatar (on | off)
avatar_image: "assets/img/frac.jpg"
avatar_description: "frac rack ðŸŽ¶"
highlighter_theme: monokai  # Theme of the syntax_highlighter [base16 |
                            # colorful | github | gruvbox | molokai |
                            # monokai | pastie | thankful_eyes | tulip ]
    
    
toolbar_priority:        # Order of the items in the toolbar (except for blog and home)
  - SpecificModuleInfo
  - DIY
  - About

  
# Collections
collections:
  dropdown:
    output: true
  items:
    output: true

